"""
TESTS is a dict with all you tests.
Keys for this will be categories' names.
Each test is dict with
    "input" -- input data for user function
    "answer" -- your right answer
    "explanation" -- not necessary key, it's using for additional info in animation.
"""

TESTS = {
    "Basics": [
        {
            "input": ['ACGTC', 'TTACTC'],
            "answer": "ACTC",
        },
        {
            "input": ['TTACTC', 'ACGTC'],
            "answer": "ACTC",
        },
        {
            "input": ['CGCTA', 'TACCG'],
            "answer": "CC,CG,TA",
        },
        {
            "input": ['GCTT', 'AAAAA'],
            "answer": "",
        },
        {
            "input": ['CGTCGTCGT', 'CGTACGT'],
            "answer": "CGTCGT",
        },
        {
            "input": ['TGCAAAACGT', 'ACGTAAAATGCA'],
            "answer": "CAAAAC,CAAAAG,CAAAAT,GAAAAC,GAAAAG,GAAAAT,TAAAAC,TAAAAG,TAAAAT",
        },
        {
            "input": ['GGGCCCAAA', 'AAACCCGGGG'],
            "answer": "AAA,CCC,GGG",
        },
    ],
    "Extra": [
        {
            "input": ('TTGGTGTCGCTAGACC', 'CGCTAGTGGGGAAT'),
            "answer": "TTGGGGAA",
        },
        {
            "input": ('GTCGCTGTGCAGGTCCGGGTTCA', 'GCGACCCGAATCCAGCTATAGGTATATGTCAGTCGGCCGTTAGGT'),
            "answer": "GCGCGTGCAGGTCCGGGTTA,GTCGCTGTGCAGTCGGGTTA",
        },
        {
            "input": ('CCCATTCACGT', 'TGGCGACCGGGATCGTACTT'),
            "answer": "CCCATCACT,CCCATTACT",
        },
        {
            "input": ('CATATGTGTACTGC', 'GCCGACCGCTGTCATTAATATACAGTTCGAA'),
            "answer": "CATATTTACTG,CATATTTATGC",
        },
        {
            "input": ('GGAGTACCATGGGCGGGACGTCACAGCCCCCAACTCA', 'AAGGTGACGCAAATGGTATATTCGCTAAGGATT'),
            "answer": "AGTACCATGGATACGCAAA,AGTACCATGGCGCTAAGAT,GGTACCATGGATACGCAAA,GGTACCATGGCGCTAAGAT",
        },
        {
            "input": ('TAGTCTTCTGGTCTAAATCCCTGCAGGAATATGCAAACTGG', 'TCCTGATCTCATGGT'),
            "answer": "TCCTGATCTCAGGT,TCCTGATCTCATGG",
        },
        {
            "input": ('AGTAATAATATGCTTCGGCTTTA', 'CGCGGGCAGTATC'),
            "answer": "CCGGCTA,CCGGCTT,GCGGCTA,GCGGCTT",
        },
        {
            "input": (
            'TGACTGACAACGACTGGAGCATCTCGTATGGTAGTTTTTCGTTATCTCTGGGACCAGGACCTTCCAAGGCTCAAGGAGGACGTGCCCGGATTAGCGCCGGGGGCTCGACATCGCTCACCACCCATGGTCGTGTTCCTCCGATGCTCCATATCCCCCGCAGGATCAGTGCTATAT',
            'GCGTTAAAAAGATACTGCCCGCTAGGTTGTTCGGTACGCTTACAGGTGGGGGACCCGACAGCTGTAATGTGTTCTAACAAGCCCCGTTGCTAAACCTCATAGAGACCCATCGCCCGCGGACAAGG'),
            "answer": "GCGAAAAAGATCTCGTAGGTTGTTCGGACGCTTAAGGTGGGGGCCCGACGCTGAATGTCACACCCCGTTTCCTCATGCCCATCCCCGCGGACAGG,GCTAAAGACTGCCCGTAGGTTGTTCGGACGCTTCAGGTGGGGACCCGAAGCGTAATGCTCACCCCGTTGTCCTCGAGCCCATCCCCGCGGACAGG",
        },
        {
            "input": (
            'ACCTGACATAAGTGACGGGTAGAGCCTCAGAGGTAGAAGTACTGGGGCCATCCAACGGCAATCGTCAAGTACCCGGAGAGCTGCACAGGGGTACACTTCGCAAGGTACCCCTAGTGTTACCGCTTGGCGTATTAACGTTGTGGTTGCGATCTTCCCCGGCAGCGCCTGG',
            'TATTCGAACTTAGGGTGTGGGCATCACGGCTACGAATTTGTCGGCCGCTAATTGTCGTCGTGAGACCTTATATCGGAGCGAATGCCCCGAACTGGGCGCTGCGCCGTCATGCTCTTGGGAG'),
            "answer": "ACGACTAGGGGGGGCTCAGGTAGAAGTCGGCCGCAATGTCGTCGGAGACTATATCGAGGAATGCCCCGAACTGGGCGCTCCCGCAGCCTGG,ATGAATTAGGGTGGCTCAGGTAGAATTGTCCCGCAATGTCGTCGGAGACCTATTCGAGGAATGCCCCGAACTGGGCGCTCCCGCAGCCTGG,TATTCGAACTAGGGTGTGGGCATCACGGCACGAAGTCCCGAAGCTCGGGACATTCGAGGAATGCCCCGAACTGGGCGCTCCCGCAGCCTGG,TATTCGAACTAGGGTGTGGGCATCACGGCTCGAAGTCCCGAATGCGGGGACCTTAAGGACGTGCCCCGAACTGGGCGCTCCCGCAGCCTGG",
        },
        {
            "input": (
            'GAGAGTTAGTAATCCTGATCCAACGCCGCGCACGGCTCCGCTAAGCTTCTAGTCAGTCATGCATCGCGTTAGGCCGGTAGTCTAGGCAGTCACCGAGCAC',
            'TAGCGGAATCCTGACCATATCCGTCGATGTACGTGTAAGTGGTGGGGACATGCCCCCACCGGCAGCGTACTTTACCTAATAAGAGAGGTCGCTCGACGCGTGAGGTATTGAGAAACCGAGTTATGACTGCTCTTTGTATAAATAGGAGCCGCGTATTGCACCGTGAAAGAGAAATAAAGCCCGTGACCCCACCGATTATTCGGATTTATTAGGTACGGATGGTGCCTTAGCTTCTGAGCGGGAACATCTGCAAACTCTGTTGTCCGGGCCGAACAAGACATAAGGTGGTGCGTGTGCCGGGGAGGAACAATTCGGCAGTACGCAACCGGTATGCGGTGAGATCATGAAGAAAGCGACAGGACTTTCGTGAAAATATCCAGAAATTTTGGAGCACGCAGACTCGACCCGCGAATCCGAAACCCAGGGCGTAAATTCTGAATATCACATAGTGATGTGAGAAATTCGTCAAACCTGAGCGTATTCGCTAGGTCTTTGCCAAACGGCCACTTCTAAGCTGCGTAACTCGCCTCGCTCAGTGGATCCAGACGATTTTTAGATCGACGATGGGCCGGCCAGATGCGCGTGGTCGGAAGATCTGCGGCAGCAGGGACATGCCAGAACGTCTTGGGCAAGAACCCCAATATTTCATGCAGTATGAGACGGACACAAGGCAGCGGTGAAGCTGCTTTCGACTCGGATACCTCCCTGGATGAATCATAGGGAACAGCGCAAACTAGCTACGTTTCCCGGGGAACATGTCGGACTTACAGGGGGTCTTTCTCAGAGGCAAGATACCAGAATAACATGTCGTCACAACAGACATCCGGTTCATCACTCTACGGTTTCTTAATTGTATAGAGAGTAACTGGGTCCATGACCTAGAAGGACGGCTGTAACGTTTTAATGGTTAACTACCCCTCCCCGGAGCATACATCGATGATGAGGTGCACCTCGTGTTTGCTACGTTACACGTTATACTGTGGGGTTCTGCTCTCGGTG'),
            "answer": "GAGAGTTAGTAATCCTGATCCAACGCCGCGCACGGCTCCGCTAAGCTTCTAGTCAGTCATGCATCGCGTTAGGCCGGTAGTCTAGGCAGTCACCGAGCAC",
        },
        {
            "input": (
            'TGTTCCACGGGATGCACTATAGGCGTGGCCTGGGAACACAACCCCCCTGGGCAAGAAGTAAGCCGCGATTATGCACGTACTGTACTTCCCTCGGAGGGGTGGTATCGGCGGCTCTGACATGTGCTCAGGGGAACGCACGAGGCAAGTGAGCGCCTTGCGTACCGTTGGTGAGGAGTAAGGCCATTCCTAGTGCCATGGGTATCCTTCGCCTGTTGGCAATGCTCCAATAAGGATCTCACAAACTGGCCTATTATTTGGTCGACCCTAGACTCCACGCGGCCCCGTGGGCCAGTAAGCATAGATACTCAACAGTTAAGACGTGGTACGTGAACCTATTAAGGCGCGTGACGGATGAATAGAAATCCCTTTGCAATCGTCCTGTCGGGAATCGTTCCGGCTTCTGAAAGTTTCTAATTGTCTTCGGAAAGTACACGAAAGCGACCCGTCCTGGTCGTTAACAATCTTTCGTATAGCCCCTGTTTCGCGGATGGCGCGTGGCAACCGGGCCGCAGCAGTTATCACTTTTTAATTGGGTAGTGGTCGCCTGCTGCCCAATTCCGGCGCCCCGC',
            'GAGCCAGTATACGTCGGTCTACAGCCGTACAATGCGCATATGGCCAGGCGGGGAATCGTTGACGTGTTGCCTTGGCTATGTAGTAGAAAGTCCTGTAAGTAAGGGCACCTGCAATCGATGTTT'),
            "answer": "GAGCCAGTATACGTCGGTCTACAGCCGTACAATGCGCATATGGCCAGGCGGGGAATCGTTGACGTGTTGCCTTGGCTATGTAGTAGAAAGTCCTGTAAGTAAGGGCACCTGCAATCGATGTTT",
        },
        {
            "input": (
            'AATTTCGTGCGTTCAAGGGCGGGATACCGGCACGCAAGTTGCGCCCTTAGTACACACTATATTCAAGGAACTCACCGAGTCGCTTGTACTTAGCCGTTGGTTAGCGGGATGCCAATTTCTCCGTGATTAGTTGCTATTGGTATCTCCTATTAAGATCCGAACGAACAACGGCGGATTTGGGTCCCAGGACCGCCGGAGCAGCAACACGGCCTCTCCTTAGTCAATGATTGCCGAATGCTAGCGAGAGGAGATTAGCTTTATCCTCCGGCTGGTCCGGCTACACCAATCATACGCTAAGCCCCTCGTTTGTGGGCAGGGAGTTCAAGCGCCCGACCCCTGACCGACATCCGAGGTATCTAAACCTGAAACCTCCGAGACGAGCCAAGTCGTAACAATGTACCAGTCAACGCGGTAGATAGTGTGACCGAGTACCAGCAGTTAACGTAGAGTGTTTGAGAGAACGACCGCATGAATTCATGCCAGCCCCTGGCACGTACGGTTCCCGTTCCATGGATGCGGTTCAATGCGGACACGATATGCGTCACGCCGGTACCGTCTTGACTGAC',
            'CGAATCCTTGATTATTGAGTGATCAGTCTCTTCAATGTAGGACCACTTGACCTCCTCACAAGTCTAAAAAAAAACGTGATACCTCTAGCCCTCCGAGCGTTACGGCTGAAGAGATCTCGGGAAGGCGGGGCGGGTACCACGAGTGTTTTTACGTGATCCATGGTTCTCACCGTTGAGCTTTTTCATTTACATCCTAAAACCTCTTTGCGTATGGAATCGAGATGCCACTGTATCCCAGTGAATACCCCCAGCTGGTGCGATCGGAATCGCCGCAGCATACAGGTATCTCAAAAGTTAAGCAGGGAATCTGTGCGAGGAGGCCCGTTGTAAAGGGTGACTCACAGCTTCGCTCAGCCACGTCAACAGTGGAATATGCCGAAGATGATGCTTCTCTAGCGTTTATGACGAACCTTGTGACTACTGTACTGAATACAGAGCATCTAATTTGTAGCTCTCTCGATCATCGGCCCCACCATTAGCCTAATTGAATTGATTCCGTGAGGGTAC'),
            "answer": "AATCCTTAAGGGATCGCCCAATTGGCCCTTGACCCTAATCAAAAAACGTGTACTTAGCCTGGTTACGGGAGAATCTCGGAAGGCGGGGCGACACGGGTTTGGTCCAGGCCCCGGAGCCAACACCTCCCTTTCATGATCGAATGCACGAAGGAATACCCCCGCTGGTCCGGAACCACATACGTACTCGTTGCAGGGATCGGCGAGGACCCGTTTAAATGACTCACAGCTCGTCAGCCAGTCAACGGGAATATGCCGAGTACCAGCGTTAACGAATGTTTGAGAAACGAGCATAATTTGAGCCTCCGTACGGCCCCCATTGCCAATGAATTGATCCGTGAGAC,AATTTGTGCGTTCAAGTAGGACCATTGCCCCTAGTAAAAAAAGGAACTCACCGAGTCGCTGTCTAGCGGGGCGGGACCAATTTTCGTGATTGTTCTATTGGTTTCTTTAATCCAAAACCCTTTGGTAGGACGAGAGCCACGTCCCAGTAATACCGTGTGCGAGGAATGCCCGCTCGGTACCAAAAGTAAGCTCTGTGGAGGAGGCCCGTGAAAGGGTGACTCACAGCCGCTCAGCCAGTCAACGGGAATATGCCGAGTACCAGCGTTAACGAAGTGTTTAGAAACGAGCATAATTTGAGCCCCTCATCGGCCCCCATAGCTAATGAAGATTCGTAGGGTAC,AATTTGTGCGTTCAAGTAGGACCATTGCCCCTCACACTAAAAAAAACGTGTACTTAGCCTGGTTACGGGAGAATCTCGGAAGGCGGGGCGACACGGGTTTGGTCCAGGCCCCGGAGCCAACACCTCCCTTTCATGATCGAATGCACGAAGGAATACCCCCGCTGGTCCGGAACCACATACGTACTCGTTGCAGGGATCGGCGAGGACCCGTTTAAATGACTCACAGCTCGTCAGCCAGTCAACGGGAATATGCCGAGTACCAGCGTTAACGAATGTTTGAGAAACGAGCATAATTTGAGCCTCCGTACGGCCCCCATTGCCAATGAATTGATCCGTGAGAC",
        },
    ]
}
