"""
TESTS is a dict with all you tests.
Keys for this will be categories' names.
Each test is dict with
    "input" -- input data for user function
    "answer" -- your right answer
    "explanation" -- not necessary key, it's using for additional info in animation.
"""

TESTS = {
    "Basics": [
        {
            "input": ['ACGTC', 'TTACTC'],
            "answer": "ACTC",
        },
        {
            "input": ['TTACTC', 'ACGTC'],
            "answer": "ACTC",
        },
        {
            "input": ['CGCTA', 'TACCG'],
            "answer": "CG,TA",
        },
        {
            "input": ['GCTT', 'AAAAA'],
            "answer": "",
        },
        {
            "input": ['CGTCGTCGT', 'CGTACGT'],
            "answer": "CGTCGT",
        },
        {
            "input": ['TGCAAAACGT', 'ACGTAAAATGCA'],
            "answer": "CAAAAT,GAAAAT,TAAAAT",
        },
    ],
    "Extra": [
        {
            "input": ['GGGCCCAAA', 'AAACCCGGGG'],
            "answer": "AAA,CCC,GGG",
        },
        {
            "input": ('TTGGTGTCGCTAGACC', 'CGCTAGTGGGGAAT'),
            "answer": "TTGGGGAA",
        },
        {
            "input": ('GTCGCTGTGCAGGTCCGGGTTCA', 'GCGACCCGAATCCAGCTATAGGTATATGTCAGTCGGCCGTTAGGT'),
            "answer": "GTCGCTGTGCAGTCGGGTTA",
        },
        {
            "input": ('CCCATTCACGT', 'TGGCGACCGGGATCGTACTT'),
            "answer": "CCCATCACT,CCCATTACT"
        },
        {
            "input": ('CATATGTGTACTGC', 'GCCGACCGCTGTCATTAATATACAGTTCGAA'),
            "answer": "CATATTTATGC",
        },
        {
            "input": ('GGAGTACCATGGGCGGGACGTCACAGCCCCCAACTCA', 'AAGGTGACGCAAATGGTATATTCGCTAAGGATT'),
            "answer": "AGTACCATGGATACGCAAA,GGTACCATGGATACGCAAA",
        },
        {
            "input": ('TAGTCTTCTGGTCTAAATCCCTGCAGGAATATGCAAACTGG', 'TCCTGATCTCATGGT'),
            "answer": "TCCTGATCTCATGG",
        },
        {
            "input": ('AGTAATAATATGCTTCGGCTTTA', 'CGCGGGCAGTATC'),
            "answer": "CCGGCTA,GCGGCTA",
        },
        {
            "input": (
                'TGACTGACAACGACTGGAGCATCTCGTATGGTAGTTTTTCGTTATCTCTGGGACCAGGACCTTCCAAGGCTCAAGGAGGACGTGCCCGGATTAGCGCCGGGGGCTCGACATCGCTCACCACCCATGGTCGTGTTCCTCCGATGCTCCATATCCCCCGCAGGATCAGTGCTATAT',
                'GCGTTAAAAAGATACTGCCCGCTAGGTTGTTCGGTACGCTTACAGGTGGGGGACCCGACAGCTGTAATGTGTTCTAACAAGCCCCGTTGCTAAACCTCATAGAGACCCATCGCCCGCGGACAAGG'),
            "answer": "GCGAAAAAGATCTCGTAGGTTGTTCGGACGCTTAAGGTGGGGGCCCGACGCTGAATGTCACACCCCGTTTCCTCATGCCCATCCCCGCGGACAGG",
        },
        {
            "input": (
                'ACCTGACATAAGTGACGGGTAGAGCCTCAGAGGTAGAAGTACTGGGGCCATCCAACGGCAATCGTCAAGTACCCGGAGAGCTGCACAGGGGTACACTTCGCAAGGTACCCCTAGTGTTACCGCTTGGCGTATTAACGTTGTGGTTGCGATCTTCCCCGGCAGCGCCTGG',
                'TATTCGAACTTAGGGTGTGGGCATCACGGCTACGAATTTGTCGGCCGCTAATTGTCGTCGTGAGACCTTATATCGGAGCGAATGCCCCGAACTGGGCGCTGCGCCGTCATGCTCTTGGGAG'),
            "answer": "ATGAATTAGGGTGGCTCAGGTAGAATTGTCCCGCAATGTCGTCGGAGACCTATTCGAGGAATGCCCCGAACTGGGCGCTCCCGCAGCCTGG,TATTCGAACTAGGGTGTGGGCATCACGGCTCGAAGTCCCGAATGCGGGGACCTTAAGGACGTGCCCCGAACTGGGCGCTCCCGCAGCCTGG",
        },
        {
            "input": (
                'GAGAGTTAGTAATCCTGATCCAACGCCGCGCACGGCTCCGCTAAGCTTCTAGTCAGTCATGCATCGCGTTAGGCCGGTAGTCTAGGCAGTCACCGAGCAC',
                'TAGCGGAATCCTGACCATATCCGTCGATGTACGTGTAAGTGGTGGGGACATGCCCCCACCGGCAGCGTACTTTACCTAATAAGAGAGGTCGCTCGACGCGTGAGGTATTGAGAAACCGAGTTATGACTGCTCTTTGTATAAATAGGAGCCGCGTATTGCACCGTGAAAGAGAAATAAAGCCCGTGACCCCACCGATTATTCGGATTTATTAGGTACGGATGGTGCCTTAGCTTCTGAGCGGGAACATCTGCAAACTCTGTTGTCCGGGCCGAACAAGACATAAGGTGGTGCGTGTGCCGGGGAGGAACAATTCGGCAGTACGCAACCGGTATGCGGTGAGATCATGAAGAAAGCGACAGGACTTTCGTGAAAATATCCAGAAATTTTGGAGCACGCAGACTCGACCCGCGAATCCGAAACCCAGGGCGTAAATTCTGAATATCACATAGTGATGTGAGAAATTCGTCAAACCTGAGCGTATTCGCTAGGTCTTTGCCAAACGGCCACTTCTAAGCTGCGTAACTCGCCTCGCTCAGTGGATCCAGACGATTTTTAGATCGACGATGGGCCGGCCAGATGCGCGTGGTCGGAAGATCTGCGGCAGCAGGGACATGCCAGAACGTCTTGGGCAAGAACCCCAATATTTCATGCAGTATGAGACGGACACAAGGCAGCGGTGAAGCTGCTTTCGACTCGGATACCTCCCTGGATGAATCATAGGGAACAGCGCAAACTAGCTACGTTTCCCGGGGAACATGTCGGACTTACAGGGGGTCTTTCTCAGAGGCAAGATACCAGAATAACATGTCGTCACAACAGACATCCGGTTCATCACTCTACGGTTTCTTAATTGTATAGAGAGTAACTGGGTCCATGACCTAGAAGGACGGCTGTAACGTTTTAATGGTTAACTACCCCTCCCCGGAGCATACATCGATGATGAGGTGCACCTCGTGTTTGCTACGTTACACGTTATACTGTGGGGTTCTGCTCTCGGTG'),
            "answer": "GAGAGTTAGTAATCCTGATCCAACGCCGCGCACGGCTCCGCTAAGCTTCTAGTCAGTCATGCATCGCGTTAGGCCGGTAGTCTAGGCAGTCACCGAGCAC",
        },
        {
            "input": (
            'TGTTCCACGGGATGCACTATAGGCGTGGCCTGGGAACACAACCCCCCTGGGCAAGAAGTAAGCCGCGATTATGCACGTACTGTACTTCCCTCGGAGGGGTGGTATCGGCGGCTCTGACATGTGCTCAGGGGAACGCACGAGGCAAGTGAGCGCCTTGCGTACCGTTGGTGAGGAGTAAGGCCATTCCTAGTGCCATGGGTATCCTTCGCCTGTTGGCAATGCTCCAATAAGGATCTCACAAACTGGCCTATTATTTGGTCGACCCTAGACTCCACGCGGCCCCGTGGGCCAGTAAGCATAGATACTCAACAGTTAAGACGTGGTACGTGAACCTATTAAGGCGCGTGACGGATGAATAGAAATCCCTTTGCAATCGTCCTGTCGGGAATCGTTCCGGCTTCTGAAAGTTTCTAATTGTCTTCGGAAAGTACACGAAAGCGACCCGTCCTGGTCGTTAACAATCTTTCGTATAGCCCCTGTTTCGCGGATGGCGCGTGGCAACCGGGCCGCAGCAGTTATCACTTTTTAATTGGGTAGTGGTCGCCTGCTGCCCAATTCCGGCGCCCCGC',
            'GAGCCAGTATACGTCGGTCTACAGCCGTACAATGCGCATATGGCCAGGCGGGGAATCGTTGACGTGTTGCCTTGGCTATGTAGTAGAAAGTCCTGTAAGTAAGGGCACCTGCAATCGATGTTT'),
            "answer": "GAGCCAGTATACGTCGGTCTACAGCCGTACAATGCGCATATGGCCAGGCGGGGAATCGTTGACGTGTTGCCTTGGCTATGTAGTAGAAAGTCCTGTAAGTAAGGGCACCTGCAATCGATGTTT",
        },
        {
            "input": (
            'AATTTCGTGCGTTCAAGGGCGGGATACCGGCACGCAAGTTGCGCCCTTAGTACACACTATATTCAAGGAACTCACCGAGTCGCTTGTACTTAGCCGTTGGTTAGCGGGATGCCAATTTCTCCGTGATTAGTTGCTATTGGTATCTCCTATTAAGATCCGAACGAACAACGGCGGATTTGGGTCCCAGGACCGCCGGAGCAGCAACACGGCCTCTCCTTAGTCAATGATTGCCGAATGCTAGCGAGAGGAGATTAGCTTTATCCTCCGGCTGGTCCGGCTACACCAATCATACGCTAAGCCCCTCGTTTGTGGGCAGGGAGTTCAAGCGCCCGACCCCTGACCGACATCCGAGGTATCTAAACCTGAAACCTCCGAGACGAGCCAAGTCGTAACAATGTACCAGTCAACGCGGTAGATAGTGTGACCGAGTACCAGCAGTTAACGTAGAGTGTTTGAGAGAACGACCGCATGAATTCATGCCAGCCCCTGGCACGTACGGTTCCCGTTCCATGGATGCGGTTCAATGCGGACACGATATGCGTCACGCCGGTACCGTCTTGACTGAC',
            'CGAATCCTTGATTATTGAGTGATCAGTCTCTTCAATGTAGGACCACTTGACCTCCTCACAAGTCTAAAAAAAAACGTGATACCTCTAGCCCTCCGAGCGTTACGGCTGAAGAGATCTCGGGAAGGCGGGGCGGGTACCACGAGTGTTTTTACGTGATCCATGGTTCTCACCGTTGAGCTTTTTCATTTACATCCTAAAACCTCTTTGCGTATGGAATCGAGATGCCACTGTATCCCAGTGAATACCCCCAGCTGGTGCGATCGGAATCGCCGCAGCATACAGGTATCTCAAAAGTTAAGCAGGGAATCTGTGCGAGGAGGCCCGTTGTAAAGGGTGACTCACAGCTTCGCTCAGCCACGTCAACAGTGGAATATGCCGAAGATGATGCTTCTCTAGCGTTTATGACGAACCTTGTGACTACTGTACTGAATACAGAGCATCTAATTTGTAGCTCTCTCGATCATCGGCCCCACCATTAGCCTAATTGAATTGATTCCGTGAGGGTAC'),
            "answer": "AATTTGTGCGTTCAAGTAGGACCATTGCCCCTCACACTAAAAAAAACGTGTACTTAGCCTGGTTACGGGAGAATCTCGGAAGGCGGGGCGACACGGGTTTGGTCCAGGCCCCGGAGCCAACACCTCCCTTTCATGATCGAATGCACGAAGGAATACCCCCGCTGGTCCGGAACCACATACGTACTCGTTGCAGGGATCGGCGAGGACCCGTTTAAATGACTCACAGCTCGTCAGCCAGTCAACGGGAATATGCCGAGTACCAGCGTTAACGAATGTTTGAGAAACGAGCATAATTTGAGCCTCCGTACGGCCCCCATTGCCAATGAATTGATCCGTGAGAC",
        },
    ]
}
